### PR TITLE
added empty gres.conf and instruction to copy it into the container

### PR DESCRIPTION
**Pull request by psteinb**
@giovtorres this is simply a wonderful repo. Thanks for sharing it. We have started to evaluate if using your repo could facilitate debuggin our slurm installation? On that note, I added an empty `gres.conf` file which is copied into the container(s). I played around with it to emulate GPU-enabled nodes. It appears to work. If you find this contribution useful, I could add more to this PR as I might research into running your setup with nvidia-docker (so that the GPU handthrough works).

### CODE REVIEW

**Comment by giovtorres** [comment]
Why not add something to `gres.conf`, even if it is simple or basic?

**Comment by psteinb** [comment]
done with 7545995

**Comment by giovtorres** [comment]
We should also update `slurm.conf` with `GresTypes=gpu` and add `Gres=gpu:titanxp:2` to the compute node parameters.

I can add it as well, [if you allow me to](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork).

**Comment by psteinb** [comment]
done with e74bb5a

**Pull request merged**
